insert into countries(country_id,name,alternative_name_1) values("can","canada","canadian");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) values("fra","france","french","francais","francaise");
insert into countries(country_id,name,alternative_name_1,alternative_name_2) values("deu","germany","german","deutschland");
insert into countries(country_id,name,alternative_name_1,alternative_name_2) values("gbr","great britain","britain","british");
insert into countries(country_id,name,alternative_name_1) values("ita","italy","italian");
insert into countries(country_id,name,alternative_name_1) values("mex","mexico","mexican");
insert into countries(country_id,name,alternative_name_1) values("rus","russia","russian");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) values("zaf","south africa","south african","s africa","s. africa","s african","s. african");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) values("che","switzerland","swiss","helvetia","confoederatio helvetica");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) values("usa","united states of america","usa","us","united states","united states america");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) values("sur","suriname","republic of suriname","republiek suriname","dutch guiana","guiana");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) values("srb","serbia","serbian","republic of serbia","republika srbija","srbija");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("lva","latvia","latvian","republic of latvia","latvijas","latvejas");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("hti","haiti","haitian","republic of haiti","ayiti","repiblik d ayiti");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("lux","luxembourg","letzeburg","grand duchy of luxembourg");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("cub","cuba","cuban","republic of cuba","republica de cuba");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("cuw","curacao","country of curacao","korsou","land curacao","pais korsou");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("cyp","Cyprus","cypriot","republic of cyprus");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("arg","argentina","argentine","argentine republic","republica argentina");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("aus","australia","australian","commonwealth of autralia");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("hnd","honduras","republic of honduras","republica de honduras");
INSERT INTO countries(country_id,name,alternative_name_1) VALUES("hkg","hong kong","hk");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("isl","iceland","island","icelandish","icelandic");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("ind","india","indian","republic of india");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("irl","ireland","eire","irish","republic of ireland");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("jam","jamaica","jamaican","jumieka");
INSERT INTO countries(country_id,name,alternative_name_1) VALUES("kwt","kuwait","state of kuwait");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("lbn","lebanon","lebanese","republic of lebanon");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("lbr","liberia","liberian","republic of liberia");
INSERT INTO countries(country_id,name,alternative_name_1) VALUES("mac","macau","macao");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("pry","paraguay","republic of paraguay","republica del paraguay","paraguai","paraguai tavakuaireta");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("col","colombia","colombian","republic of colombia","republica de colombia");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("com","comoros","union of the comoros","komori","comores","udzima wa komori","union des comores");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("grc","greece","greek","hellenic republic","elliniki dimokratia");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("pol","poland","polish","republic of poland","rzeczpospolita polska","polska");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("esp","spain","spanish","kingdom of spain","espana","reino de espana");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("bel","belgium","belgian","kingdom of belgium","belgie","belgique","belgien");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("aut","austria","austrian","republic of austria","osterreich","republik osterreich");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("dnk","denmark","danish","danmark");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("egy","egypt","egyptian","arab republic of egypt");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("fin","finland","republic of finland","finnish","suomi","suomen tasavalta","republiken finland");
insert into countries(country_id,name,alternative_name_1,alternative_name_2) values("gbr","great britain","britain","british");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("nld","netherlands","netherland","kingdom of the netherlands","the netherlands","nederlanden","dutch");
