INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("can_cent_5","can_cent",5,"nickel","nickels");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("can_cent_10","can_cent",10,"dime","dimes");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("can_cent_20","can_cent",20);
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("can_cent_25","can_cent",25,"quarter","quarters");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("can_cent_50","can_cent",50,"half","halves");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("can_sovereign_1","can_sovereign",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("can_dollar_1","can_dollar",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("can_dollar_5","can_dollar",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("can_dollar_10","can_dollar",10);
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("can_maple_1_oz","can_maple",50,"1 oz maple","1");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("can_maple_fractional_1_2_oz","can_maple",20,"1/2 oz maple","1/2");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("can_maple_fractional_1_4_oz","can_maple",10,"1/4 oz maple","1/4");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("can_maple_fractional_1_10_oz","can_maple",5,"1/10 oz maple","1/10");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("can_maple_fractional_1_20_oz","can_maple",1,"1/20 oz maple","1/20");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("can_maple_1_gram","can_maple",0.5,"1 gram maple","1");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("fra_centime_20","fra_centime",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("fra_centime_50","fra_centime",50);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("fra_franc_1","fra_franc",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("fra_franc_2","fra_franc",2);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("fra_franc_5","fra_franc",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("fra_franc_10","fra_franc",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("fra_franc_20","fra_franc",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("fra_franc_50","fra_franc",50);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("fra_franc_100","fra_franc",100);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("deu_pfennig_20","deu_pfennig",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("deu_pfennig_50","deu_pfennig",50);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("deu_mark_1","deu_mark",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("deu_mark_2","deu_mark",2);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("deu_mark_3","deu_mark",3);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("deu_mark_5","deu_mark",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("deu_mark_10","deu_mark",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("deu_mark_20","deu_mark",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("ita_centesimo_20","ita_centesimo",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("ita_centesimo_50","ita_centesimo",50);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("ita_lira_1","ita_lira",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("ita_lira_2","ita_lira",2);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("ita_lira_5","ita_lira",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("ita_lira_10","ita_lira",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("ita_lira_20","ita_lira",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("ita_lira_50","ita_lira",50);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("ita_lira_100","ita_lira",100);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("ita_lira_500","ita_lira",500);
INSERT INTO face_values(value_id,denomination_id,value,name) VALUES("che_franc_fractional_1_2","che_franc",0.5,"1/2");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("che_franc_1","che_franc",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("che_franc_2","che_franc",2);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("che_franc_5","che_franc",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("che_franc_10","che_franc",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("che_franc_20","che_franc",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("che_franc_100","che_franc",100);
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("usa_cent_10","usa_cent",10,"dime","dimes");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("usa_cent_25","usa_cent",25,"quarter","quarters");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("usa_cent_50","usa_cent",50,"half","halves");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("usa_dollar_1","usa_dollar",1,"dollar","dollars");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("usa_bullion_fractional_1_10_oz","usa_bullion",0.1,"1/10 oz bullion","1/10");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("usa_bullion_fractional_1_4_oz","usa_bullion",0.25,"1/4 oz bullion","1/4");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("usa_bullion_fractional_1_2_oz","usa_bullion",0.5,"1/2 oz bullion","1/2");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("usa_bullion_1_oz","usa_bullion",1,"1 oz bullion","1");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("rus_kopek_5","rus_kopek",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("rus_kopek_10","rus_kopek",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("rus_kopek_15","rus_kopek",15);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("rus_kopek_20","rus_kopek",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("rus_kopek_25","rus_kopek",25);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("rus_kopek_50","rus_kopek",50);
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1,alternative_name_2) VALUES("rus_ruble_fractional_1_2","rus_ruble",0.5,"1/2 (poltina)","1/2","poltina");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("rus_ruble_1","rus_ruble",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("rus_ruble_3","rus_ruble",3);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("rus_ruble_5","rus_ruble",5);
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1,alternative_name_2) VALUES("rus_ruble_fractional_7_1_2","rus_ruble",7.5,"7-1/2","7 1/2","15/2");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("rus_ruble_10","rus_ruble",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("rus_ruble_15","rus_ruble",15);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("rus_ruble_25","rus_ruble",25);
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1,alternative_name_2) VALUES("rus_ruble_fractional_37_1_2","rus_ruble",37.5,"37-1/2","37 1/2","75/2");
INSERT INTO face_values(value_id,denomination_id,value,name) VALUES("mex_real_fractional_1_4","mex_real",0.25,"1/4");
INSERT INTO face_values(value_id,denomination_id,value,name) VALUES("mex_real_fractional_1_2","mex_real",0.5,"1/2");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_real_1","mex_real",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_real_2","mex_real",2);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_real_4","mex_real",4);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_real_8","mex_real",8);
INSERT INTO face_values(value_id,denomination_id,value,name) VALUES("mex_escudo_fractional_1_2","mex_escudo",0.5,"1/2");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_escudo_1","mex_escudo",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_escudo_2","mex_escudo",2);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_escudo_4","mex_escudo",4);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_escudo_8","mex_escudo",8);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_centavo_5","mex_centavo",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_centavo_10","mex_centavo",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_centavo_20","mex_centavo",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_centavo_50","mex_centavo",50);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_peso_1","mex_peso",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_peso_2","mex_peso",2);
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1,alternative_name_2) VALUES("mex_peso_fractional_2_1_2","mex_peso",2.5,"2-1/2","2 1/2","5/2");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_peso_5","mex_peso",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_peso_10","mex_peso",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_peso_20","mex_peso",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("mex_peso_50","mex_peso",50);
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("gbr_britannia_fractional_1_10_oz","gbr_britannia",10,"1/10 oz britannia","1/10");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("gbr_britannia_fractional_1_4_oz","gbr_britannia",25,"1/4 oz britannia","1/4");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("gbr_britannia_fractional_1_2_oz","gbr_britannia",50,"1/2 oz britannia","1/2");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("gbr_britannia_1 oz","gbr_britannia",100,"1 oz britannia","1");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("zaf_krugerrand_1_oz","zaf_krugerrand",1,"1 oz krugerrand","1");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("zaf_krugerrand_fractional_1_2_oz","zaf_krugerrand",0.5,"1/2 oz krugerrand","1/2");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("zaf_krugerrand_fractional_1_4_oz","zaf_krugerrand",0.25,"1/4 oz krugerrand","1/4");
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1) VALUES("zaf_krugerrand_fractional_1_10_oz","zaf_krugerrand",0.1,"1/10 oz krugerrand","1/10");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("sur_gulden_1","sur_gulden",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("srb_para_50","srb_para",50);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("srb_dinar_1","srb_dinar",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("srb_dinar_2","srb_dinar",2);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("srb_dinar_5","srb_dinar",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("srb_dinar_10","srb_dinar",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("srb_dinar_20","srb_dinar",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("lva_lats_1","lva_lats",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("lva_lats_2","lva_lats",2);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("lva_lats_5","lva_lats",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hti_centime_10","hti_centime",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hti_centime_20","hti_centime",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hti_centime_50","hti_centime",50);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hti_gourde_1","hti_gourde",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("lux_franc_5","lux_franc",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("lux_franc_10","lux_franc",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("lux_franc_20","lux_franc",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("lux_franc_50","lux_franc",50);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("lux_franc_100","lux_franc",100);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cub_peso_1","cub_peso",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cub_peso_2","cub_peso",2);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cub_peso_4","cub_peso",4);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cub_peso_5","cub_peso",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cub_peso_10","cub_peso",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cub_peso_20","cub_peso",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cub_centavo_10","cub_centavo",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cub_centavo_20","cub_centavo",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cub_centavo_25","cub_centavo",25);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cub_centavo_40","cub_centavo",40);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cub_centavo_50","cub_centavo",50);
INSERT INTO face_values(value_id,denomination_id,value,name) VALUES("cuw_gulden_fractional_1_10","cuw_gulden",0.1,"1/10");
INSERT INTO face_values(value_id,denomination_id,value,name) VALUES("cuw_gulden_fractional_1_4","cuw_gulden",0.25,"1/4");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cuw_gulden_1","cuw_gulden",1);
INSERT INTO face_values(value_id,denomination_id,value,name,alternative_name_1,alternative_name_2) VALUES("cuw_gulden_fractional_2_1_2","cuw_gulden",2.5,"2-1/2","2 1/2","5/2");
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cyp_piastre_3","cyp_piastre",3);
INSERT INTO face_values(value_id,denomination_id,name,alternative_name_1,alternative_name_2,value) VALUES("cyp_piastre_fractional_4_1_2","cyp_piastre","4-1/2","4 1/2","9/2",4.5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cyp_piastre_9","cyp_piastre",9);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cyp_piastre_18","cyp_piastre",18);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("cyp_piastre_45","cyp_piastre",45);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("arg_centavo_10","arg_centavo",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("arg_centavo_20","arg_centavo",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("arg_centavo_50","arg_centavo",50);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("arg_peso_1","arg_peso",1);
INSERT INTO face_values(value_id,denomination_id,name,value) VALUES("arg_argentino_fractional_1_2","arg_argentino","1/2",0.5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("arg_argentino_1","arg_argentino",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("aus_penny_3","aus_penny",3);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("aus_penny_6","aus_penny",6);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("aus_shilling_1","aus_shilling",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("aus_crown_1","aus_crown",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("aus_florin_1","aus_florin",1);
INSERT INTO face_values(value_id,denomination_id,name,value) VALUES("aus_sovereign_fractional_1_2","aus_sovereign","1/2",0.5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("aus_sovereign_1","aus_sovereign",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hnd_centavo_5","hnd_centavo",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hnd_centavo_10","hnd_centavo",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hnd_centavo_25","hnd_centavo",25);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hnd_centavo_50","hnd_centavo",50);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hnd_peso_1","hnd_peso",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hnd_centavo_20","hnd_centavo",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hnd_lempira_1","hnd_lempira",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hnd_peso_5","hnd_peso",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hnd_peso_10","hnd_peso",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hnd_peso_20","hnd_peso",20);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hkg_cent_5","hkg_cent",5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hkg_cent_10","hkg_cent",10);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hkg_cent_20","hkg_cent",20);
INSERT INTO face_values(value_id,denomination_id,name,value) VALUES("hkg_dollar_fractional_1_2","hkg_dollar","1/2",0.5);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hkg_dollar_1","hkg_dollar",1);
INSERT INTO face_values(value_id,denomination_id,value) VALUES("hkg_cent_50","hkg_cent",50);
